"""add reports and report_images tables

Revision ID: 007392aef4d8
Revises: 1462c8f3c1ae
Create Date: 2026-03-06 20:10:27.675719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007392aef4d8'
down_revision = '1462c8f3c1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_req_id', sa.String(length=50), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('radiographer_id', sa.Integer(), nullable=True),
    sa.Column('radiologist_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('radiologist_tone', sa.Text(), nullable=True),
    sa.Column('radiologist_text', sa.Text(), nullable=False),
    sa.Column('doctor_tone', sa.Text(), nullable=True),
    sa.Column('patient_tone', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['radiographer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['radiologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id')
    )
    op.create_table('report_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_images')
    op.drop_table('reports')
    # ### end Alembic commands ###
