"""update reports keep radiologist_text and add content

Revision ID: 0567b1c5860a
Revises: 007392aef4d8
Create Date: 2026-03-06 21:53:58.980331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0567b1c5860a'
down_revision = '007392aef4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.alter_column('radiographer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('radiologist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('radiologist_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('doctor_tone')
        batch_op.drop_column('radiologist_tone')
        batch_op.drop_column('patient_tone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_tone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radiologist_tone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('doctor_tone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('radiologist_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('radiologist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('radiographer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###
