"""add radiologist_id to prescriptions

Revision ID: 1462c8f3c1ae
Revises: 22d17f7c7408
Create Date: 2026-03-06 15:09:02.277800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1462c8f3c1ae'
down_revision = '22d17f7c7408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radiologist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['radiologist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('radiologist_id')

    # ### end Alembic commands ###
