"""make prescription-report bidirectional one-to-one

Revision ID: 7ea86d35c5c9
Revises: ab5e49ad7ef1
Create Date: 2026-03-08 15:23:02.486238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea86d35c5c9'
down_revision = 'ab5e49ad7ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prescriptions_report_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('prescriptions_report_id_fkey'), type_='foreignkey')
        batch_op.drop_column('report_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('prescriptions_report_id_fkey'), 'reports', ['report_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('prescriptions_report_id_key'), ['report_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
