"""update reports

Revision ID: ab5e49ad7ef1
Revises: d292369b2235
Create Date: 2026-03-08 14:18:51.788420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab5e49ad7ef1'
down_revision = 'd292369b2235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanned_images')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['report_id'])
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('report_id')

    op.create_table('scanned_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scan_req_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('radiographer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('scanned_images_prescription_id_fkey')),
    sa.ForeignKeyConstraint(['radiographer_id'], ['users.id'], name=op.f('scanned_images_radiographer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scanned_images_pkey'))
    )
    # ### end Alembic commands ###
