"""update reports

Revision ID: d292369b2235
Revises: 9a29a20cc23b
Create Date: 2026-03-08 02:40:55.983521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd292369b2235'
down_revision = '9a29a20cc23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('scan_req_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('radiologist_id', sa.Integer(), nullable=True),
    sa.Column('radiographer_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('reply_message', sa.Text(), nullable=True),
    sa.Column('read_back_verification', sa.Boolean(), nullable=True),
    sa.Column('send_to_radiologist', sa.Boolean(), nullable=False),
    sa.Column('send_to_doctor', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['radiographer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['radiologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('report_images_report_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('organ', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('analysis_time_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('classification', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('detection', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('segmentation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('images')
        batch_op.drop_column('segmentation')
        batch_op.drop_column('detection')
        batch_op.drop_column('classification')
        batch_op.drop_column('summary')
        batch_op.drop_column('analysis_time_ms')
        batch_op.drop_column('organ')
        batch_op.drop_column('scan_type')

    with op.batch_alter_table('report_images', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('report_images_report_id_fkey'), 'reports', ['report_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('image_type')

    op.drop_table('notices')
    # ### end Alembic commands ###
